const DEFAULT_FILTER_START_PRICE = 200;
const DEFAULT_FILTER_END_PRICE = 1500;

const SORT_FROM_LOWEST_TO_HIGHEST = {
  name: "From lowest to highest",
  value: -1,
};

const SORT_FROM_HIGHEST_TO_LOWEST = {
  name: "From highest to lowest",
  value: 1,
};

const SORT_OPTIONS = [SORT_FROM_LOWEST_TO_HIGHEST, SORT_FROM_HIGHEST_TO_LOWEST];

export {
  DEFAULT_FILTER_START_PRICE,
  DEFAULT_FILTER_END_PRICE,
  SORT_FROM_LOWEST_TO_HIGHEST,
  SORT_FROM_HIGHEST_TO_LOWEST,
  SORT_OPTIONS,
};
